{pkgs, ...}: let
  # Wallpapers come from the nix store, so they exist on every machine
  # regardless of where this repo is checked out.
  wallpapers = pkgs.runCommand "wallpapers" {} ''
    mkdir -p $out
    cp ${../../dotfiles/wallpaper}/*.jpg $out/
  '';
in {
  home.packages = [
    (pkgs.writeShellScriptBin "random-wallpaper"
      ''
        shopt -s nullglob

        files=(${wallpapers}/*.jpg)
        count=''${#files[@]}

        if (( count == 0 )); then
          echo "No JPG files found in ${wallpapers}"
          exit 1
        fi

        ${pkgs.feh}/bin/feh --bg-scale "''${files[RANDOM % count]}"
      '')
  ];

  # betterlockscreen -l shows a pre-rendered image from ~/.cache/betterlockscreen,
  # which otherwise has to be generated by hand with `betterlockscreen -u`.
  # This regenerates the cache on login whenever the wallpaper set changes
  # (the store path in the marker file goes stale). It must run inside the
  # graphical session because betterlockscreen queries X for the resolution.
  systemd.user.services.betterlockscreen-cache = {
    Unit = {
      Description = "Generate betterlockscreen wallpaper cache";
      After = ["graphical-session.target"];
      PartOf = ["graphical-session.target"];
    };
    Service = {
      Type = "oneshot";
      ExecStart = pkgs.writeShellScript "betterlockscreen-cache" ''
        marker="$HOME/.cache/betterlockscreen/.wallpaper-source"
        if [ "$(cat "$marker" 2>/dev/null)" != "${wallpapers}" ]; then
          ${pkgs.betterlockscreen}/bin/betterlockscreen -u ${wallpapers}
          echo "${wallpapers}" > "$marker"
        fi
      '';
    };
    Install.WantedBy = ["graphical-session.target"];
  };
}
