{pkgs, ...}: let
  # Wallpapers come from the nix store, so they exist on every machine
  # regardless of where this repo is checked out.
  wallpapers = pkgs.runCommand "wallpapers" {} ''
    mkdir -p $out
    cp ${../../dotfiles/wallpaper}/*.jpg $out/
  '';
in {
  home.packages = [
    (pkgs.writeShellScriptBin "random-wallpaper"
      ''
        shopt -s nullglob

        files=(${wallpapers}/*.jpg)
        count=''${#files[@]}

        if (( count == 0 )); then
          echo "No JPG files found in ${wallpapers}"
          exit 1
        fi

        ${pkgs.feh}/bin/feh --bg-scale "''${files[RANDOM % count]}"
      '')
  ];

  # betterlockscreen -l shows a pre-rendered image from ~/.cache/betterlockscreen,
  # which otherwise has to be generated by hand with `betterlockscreen -u`.
  # This regenerates the cache on login whenever it went stale. It must run
  # inside the graphical session because betterlockscreen queries X for the
  # resolution.
  #
  # The marker holds the wallpaper store path *and* the monitor layout: the
  # images are rendered once at whatever size X reported back then, so a cache
  # built on a 1080p screen stays 1080p - and comes out stretched - after the
  # machine moves to a 1440p one. Keying on the store path alone never noticed
  # that, which is how amd-desktop ended up locking with a 1920x1080 image
  # cached for a monitor (HDMI-0) it no longer has.
  systemd.user.services.betterlockscreen-cache = {
    Unit = {
      Description = "Generate betterlockscreen wallpaper cache";
      After = ["graphical-session.target"];
      PartOf = ["graphical-session.target"];
    };
    Service = {
      Type = "oneshot";
      ExecStart = pkgs.writeShellScript "betterlockscreen-cache" ''
        export PATH=${pkgs.lib.makeBinPath [pkgs.xrandr pkgs.coreutils pkgs.gawk pkgs.betterlockscreen]}:$PATH

        marker="$HOME/.cache/betterlockscreen/.wallpaper-source"

        layout() {
          xrandr --listmonitors | awk 'NR > 1 {printf "%s:%s ", $2, $3}'
        }

        # Hosts that force a mode do it from i3's startup commands, which can
        # land after this unit starts. Wait for the layout to stop changing so
        # the cache is not rendered against the pre-xrandr mode.
        current=$(layout)
        for _ in $(seq 10); do
          sleep 2
          next=$(layout)
          [ "$next" = "$current" ] && break
          current=$next
        done

        key="${wallpapers} $current"
        if [ "$(cat "$marker" 2>/dev/null)" != "$key" ]; then
          betterlockscreen -u ${wallpapers} && printf '%s' "$key" >"$marker"
        fi
      '';
    };
    Install.WantedBy = ["graphical-session.target"];
  };
}
